import {
    LayoutTemplate,
    FileText,
    Sparkles,
    MessageSquare,
    Image,
    Users,
    GitCommit,
    Info,
    MapPin,
    Megaphone,
    Grid,
    Code,
    Layout,
    GalleryHorizontal,
    Columns,
    Heading,
    AlignLeft,
    AlertCircle,
    GraduationCap,
    Wrench,
    BookOpen,
    Building2,
    List,
    Quote,
    Building,
    BarChart,
    Share2,
    Grid3x3,
    LayoutDashboard,
    PlayCircle,
    Youtube,
    UserCheck,
    ArrowRight,
    Clock,
    HelpCircle,
    Download,
    CreditCard,
    Phone,
    Map,
    Bell,
    Mail,
    Minus,
    Maximize,
    type LucideIcon,
    CheckSquare,
    ListOrdered,
    Type,
    CheckCircle2,
    CircleDot,
    MousePointerClick,
    BoxSelect,
    FormInput
} from "lucide-react"
import type { BlockKind } from "./types"

export interface BlockCategory {
    id: string
    nameAr: string
    nameEn: string
    icon: LucideIcon
    blocks: {
        kind: BlockKind
        labelAr: string
        labelEn: string
        descriptionAr: string
        descriptionEn: string
        icon: LucideIcon
    }[]
}

export const blockCategories: BlockCategory[] = [
    {
        id: "hero",
        nameEn: "Hero Sections",
        nameAr: "الأقسام الرئيسية",
        icon: LayoutTemplate,
        blocks: [
            {
                kind: "hero-basic",
                labelAr: "Hero أساسي",
                labelEn: "Basic Hero",
                descriptionAr: "قسم رئيسي بسيط مع عنوان وأزرار",
                descriptionEn: "Simple hero section with title and buttons",
                icon: Layout,
            },
            {
                kind: "hero-slider",
                labelAr: "Hero Slider",
                labelEn: "Hero Slider",
                descriptionAr: "سلايدر بملء الشاشة مع صور متعددة",
                descriptionEn: "Full-screen slider with multiple images",
                icon: GalleryHorizontal,
            },
            {
                kind: "hero-split",
                labelAr: "Hero منقسم",
                labelEn: "Split Hero",
                descriptionAr: "قسم رئيسي بتصميم منقسم",
                descriptionEn: "Split design hero section",
                icon: Columns,
            },
        ],
    },
    {
        id: "content",
        nameEn: "Content",
        nameAr: "المحتوى",
        icon: FileText,
        blocks: [
            {
                kind: "section-header",
                labelAr: "عنوان قسم",
                labelEn: "Section Header",
                descriptionAr: "عنوان ووصف للقسم",
                descriptionEn: "Section title and description",
                icon: Heading,
            },
            {
                kind: "rich-text",
                labelAr: "نص غني",
                labelEn: "Rich Text",
                descriptionAr: "فقرة نصية مع تنسيق",
                descriptionEn: "Text paragraph with formatting",
                icon: AlignLeft,
            },
            {
                kind: "image-with-text",
                labelAr: "صورة + نص",
                labelEn: "Image & Text",
                descriptionAr: "صورة مع نص جانبي",
                descriptionEn: "Image with side text",
                icon: Image,
            },
            {
                kind: "highlight-banner",
                labelAr: "شريط مميز",
                labelEn: "Highlight Banner",
                descriptionAr: "رسالة مهمة بارزة",
                descriptionEn: "Prominent important message",
                icon: AlertCircle,
            },
            {
                kind: "about-section",
                labelAr: "قسم من نحن",
                labelEn: "About Section",
                descriptionAr: "قسم تعريفي متكامل",
                descriptionEn: "Comprehensive about section",
                icon: Info,
            },
        ],
    },
    {
        id: "features",
        nameEn: "Features & Services",
        nameAr: "المميزات والخدمات",
        icon: Sparkles,
        blocks: [
            {
                kind: "programs-grid",
                labelAr: "شبكة البرامج",
                labelEn: "Programs Grid",
                descriptionAr: "عرض البرامج التعليمية",
                descriptionEn: "Display educational programs",
                icon: GraduationCap,
            },
            {
                kind: "services-list",
                labelAr: "قائمة الخدمات",
                labelEn: "Services List",
                descriptionAr: "عرض الخدمات المتاحة",
                descriptionEn: "Display available services",
                icon: Wrench,
            },
            {
                kind: "curriculum-overview",
                labelAr: "نظرة عامة على المنهج",
                labelEn: "Curriculum Overview",
                descriptionAr: "عرض المناهج الدراسية",
                descriptionEn: "Display curriculum overview",
                icon: BookOpen,
            },
            {
                kind: "departments-grid",
                labelAr: "شبكة الأقسام",
                labelEn: "Departments Grid",
                descriptionAr: "عرض الأقسام مع صور",
                descriptionEn: "Display departments with images",
                icon: Building2,
            },
            {
                kind: "icon-points",
                labelAr: "نقاط بأيقونات",
                labelEn: "Icon Points",
                descriptionAr: "مميزات مع أيقونات",
                descriptionEn: "Features with icons",
                icon: List,
            },
        ],
    },
    {
        id: "social-proof",
        nameEn: "Social Proof",
        nameAr: "الإثبات الاجتماعي",
        icon: MessageSquare,
        blocks: [
            {
                kind: "testimonials",
                labelAr: "آراء العملاء",
                labelEn: "Testimonials",
                descriptionAr: "شبكة أو سلايدر لآراء العملاء",
                descriptionEn: "Testimonials grid or slider",
                icon: Quote,
            },
            {
                kind: "logos-strip",
                labelAr: "شريط الشعارات",
                labelEn: "Logos Strip",
                descriptionAr: "عرض شعارات الشركاء",
                descriptionEn: "Display partner logos",
                icon: Building,
            },
            {
                kind: "stats",
                labelAr: "إحصائيات",
                labelEn: "Statistics",
                descriptionAr: "أرقام وإنجازات",
                descriptionEn: "Numbers and achievements",
                icon: BarChart,
            },
            {
                kind: "social-icons",
                labelAr: "أيقونات اجتماعية",
                labelEn: "Social Icons",
                descriptionAr: "روابط وسائل التواصل الاجتماعي",
                descriptionEn: "Social media links",
                icon: Share2,
            },
        ],
    },
    {
        id: "media",
        nameEn: "Media",
        nameAr: "الوسائط",
        icon: Image,
        blocks: [
            {
                kind: "gallery-grid",
                labelAr: "معرض الصور",
                labelEn: "Photo Gallery",
                descriptionAr: "شبكة من الصور",
                descriptionEn: "Grid of photos",
                icon: Grid3x3,
            },
            {
                kind: "gallery-masonry",
                labelAr: "معرض حر",
                labelEn: "Masonry Gallery",
                descriptionAr: "معرض بتصميم حر",
                descriptionEn: "Masonry layout gallery",
                icon: LayoutDashboard,
            },
            {
                kind: "video-highlight",
                labelAr: "فيديو مميز",
                labelEn: "Video Highlight",
                descriptionAr: "عرض فيديو بارز",
                descriptionEn: "Featured video display",
                icon: PlayCircle,
            },
            {
                kind: "video-embed",
                labelAr: "فيديو مضمن",
                labelEn: "Video Embed",
                descriptionAr: "تضمين فيديو من YouTube",
                descriptionEn: "Embed YouTube video",
                icon: Youtube,
            },
        ],
    },
    {
        id: "team",
        nameEn: "Team & People",
        nameAr: "الفريق والأشخاص",
        icon: Users,
        blocks: [
            {
                kind: "staff-grid",
                labelAr: "شبكة الطاقم",
                labelEn: "Staff Grid",
                descriptionAr: "عرض أعضاء الفريق",
                descriptionEn: "Display team members",
                icon: Users,
            },
            {
                kind: "board-or-team-list",
                labelAr: "قائمة الفريق",
                labelEn: "Team List",
                descriptionAr: "قائمة أعضاء اللجنة",
                descriptionEn: "Committee members list",
                icon: UserCheck,
            },
        ],
    },
    {
        id: "process",
        nameEn: "Process & Timeline",
        nameAr: "العملية والجدول الزمني",
        icon: ListOrdered,
        blocks: [
            {
                kind: "steps-horizontal",
                labelAr: "خطوات أفقية",
                labelEn: "Horizontal Steps",
                descriptionAr: "عرض الخطوات بشكل أفقي",
                descriptionEn: "Display steps horizontally",
                icon: ArrowRight,
            },
            {
                kind: "timeline-vertical",
                labelAr: "جدول زمني",
                labelEn: "Timeline",
                descriptionAr: "عرض الأحداث بشكل زمني",
                descriptionEn: "Display events chronologically",
                icon: Clock,
            },
        ],
    },
    {
        id: "info",
        nameEn: "Information",
        nameAr: "معلومات",
        icon: Info,
        blocks: [
            {
                kind: "faq-accordion",
                labelAr: "أسئلة شائعة",
                labelEn: "FAQ",
                descriptionAr: "أسئلة وأجوبة قابلة للطي",
                descriptionEn: "Collapsible Q&A",
                icon: HelpCircle,
            },
            {
                kind: "downloads-list",
                labelAr: "قائمة التحميلات",
                labelEn: "Downloads List",
                descriptionAr: "ملفات للتحميل",
                descriptionEn: "Files for download",
                icon: Download,
            },
            {
                kind: "pricing-table",
                labelAr: "جدول الأسعار",
                labelEn: "Pricing Table",
                descriptionAr: "عرض الخطط والأسعار",
                descriptionEn: "Display plans and pricing",
                icon: CreditCard,
            },
        ],
    },
    {
        id: "contact",
        nameEn: "Contact & Location",
        nameAr: "التواصل والموقع",
        icon: MapPin,
        blocks: [
            {
                kind: "contact-section",
                labelAr: "قسم التواصل",
                labelEn: "Contact Section",
                descriptionAr: "معلومات الاتصال",
                descriptionEn: "Contact information",
                icon: Phone,
            },
            {
                kind: "map",
                labelAr: "خريطة",
                labelEn: "Map",
                descriptionAr: "عرض الموقع على الخريطة",
                descriptionEn: "Display location on map",
                icon: Map,
            },
        ],
    },
    {
        id: "cta",
        nameEn: "Call to Action",
        nameAr: "دعوة لاتخاذ إجراء",
        icon: Megaphone,
        blocks: [
            {
                kind: "cta-strip",
                labelAr: "شريط CTA",
                labelEn: "CTA Strip",
                descriptionAr: "دعوة للعمل بارزة",
                descriptionEn: "Prominent call to action",
                icon: Bell,
            },
            {
                kind: "newsletter-signup",
                labelAr: "اشتراك النشرة",
                labelEn: "Newsletter Signup",
                descriptionAr: "نموذج اشتراك بالنشرة",
                descriptionEn: "Newsletter subscription form",
                icon: Mail,
            },
        ],
    },
    {
        id: "layout",
        nameEn: "Layout",
        nameAr: "التخطيط",
        icon: Grid,
        blocks: [
            {
                kind: "columns",
                labelAr: "أعمدة",
                labelEn: "Columns",
                descriptionAr: "تقسيم المحتوى إلى أعمدة",
                descriptionEn: "Split content into columns",
                icon: Columns,
            },
            {
                kind: "grid",
                labelAr: "شبكة",
                labelEn: "Grid",
                descriptionAr: "عرض المحتوى في شبكة",
                descriptionEn: "Display content in a grid",
                icon: Grid,
            },
            {
                kind: "divider",
                labelAr: "فاصل",
                labelEn: "Divider",
                descriptionAr: "خط فاصل بين الأقسام",
                descriptionEn: "Line separator between sections",
                icon: Minus,
            },
            {
                kind: "spacer",
                labelAr: "مسافة",
                labelEn: "Spacer",
                descriptionAr: "مسافة فارغة",
                descriptionEn: "Empty space",
                icon: Maximize,
            },
        ],
    },
    {
        id: "forms",
        nameEn: "Forms",
        nameAr: "النماذج",
        icon: FormInput,
        blocks: [
            {
                kind: "form-container",
                labelAr: "حاوية نموذج",
                labelEn: "Form Container",
                descriptionAr: "حاوية لإنشاء النماذج",
                descriptionEn: "Container for building forms",
                icon: FormInput,
            },
            {
                kind: "form-input",
                labelAr: "حقل إدخال",
                labelEn: "Input Field",
                descriptionAr: "حقل نصي بسيط",
                descriptionEn: "Simple text input",
                icon: Type,
            },
            {
                kind: "form-textarea",
                labelAr: "منطقة نص",
                labelEn: "Text Area",
                descriptionAr: "حقل نصي متعدد الأسطر",
                descriptionEn: "Multi-line text input",
                icon: Type,
            },
            {
                kind: "form-select",
                labelAr: "قائمة منسدلة",
                labelEn: "Select Menu",
                descriptionAr: "قائمة خيارات",
                descriptionEn: "Dropdown menu",
                icon: List,
            },
            {
                kind: "form-checkbox",
                labelAr: "مربع اختيار",
                labelEn: "Checkbox",
                descriptionAr: "خيار نعم/لا",
                descriptionEn: "Yes/No option",
                icon: CheckSquare,
            },
            {
                kind: "form-radio",
                labelAr: "زر اختيار",
                labelEn: "Radio Button",
                descriptionAr: "اختيار واحد من متعدد",
                descriptionEn: "Single choice from multiple",
                icon: CircleDot,
            },
            {
                kind: "form-button",
                labelAr: "زر نموذج",
                labelEn: "Form Button",
                descriptionAr: "زر إرسال أو إجراء",
                descriptionEn: "Submit or action button",
                icon: MousePointerClick,
            },
        ],
    },
    {
        id: "advanced",
        nameEn: "Advanced",
        nameAr: "متقدم",
        icon: Code,
        blocks: [
            {
                kind: "custom-html",
                labelAr: "HTML مخصص",
                labelEn: "Custom HTML",
                descriptionAr: "محتوى HTML مخصص",
                descriptionEn: "Custom HTML content",
                icon: Code,
            },
        ],
    },
]
